### ISSUE TITLE
Export as CSV

### ISSUE THREAD

**Issue by joeltio** [AY2425S1-CS2103-F10-3/tp#158]
Allow the user to export all the contacts as a CSV file so that the user may view it easily in Microsoft Excel.

Click on File and select "Export as CSV". Then, the data will be stored in `./addressBook.csv` next to the existing `addressBook.json`.

The user will be notified that it was exported successfully with a dialog.

**Comment by Nicholas-Cheng-De-Fei** [comment]
Add a command `export t/<File Type>` to determine which file type the data should be exported into
