### ISSUE TITLE
Bug: There are 2 enumerables with the same name for different functions 

### ISSUE THREAD

**Issue by ITLimJiaWei** [AY2425S1-CS2103-F10-3/tp#248]
![image](https://github.com/user-attachments/assets/65d12075-c1f9-4932-b53a-172a6c7f8ec6)

**Comment by joeltio** [comment]
I don't see anything wrong with this. The variables are `private` and `static`. They are used as convenience variables within their own contexts.

**Comment by ITLimJiaWei** [comment]
Good point, I’ll close the issue
