### ISSUE TITLE
[PE-D][Tester B] 2 or more persons with the same phone number and email can be added, does not check for uniqueness in email and phone

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F10-3/tp#321]
## Expectation
As a user, I would expect that 2 persons cannot have the same telephone number, since in real life, everyone's phone number or email should be unique. 

## Actual behavior
Currently, uniqueness is enforced on names but not phone numbers, hence it is possible to have 2 persons with different names but the same phone number and email address.

This could lead to some user errors like accidentally assigning duplicate phone and email due to carelessness, which can lead to faulty data. Preventing this could be a better product design choice.

## How to reproduce
Run the following code to add 2 persons with different name but all other fields same (including phone number)
- `add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney`
- `add n/Johnny Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 t/friends t/owesMoney`

![image.png](https://raw.githubusercontent.com/chuajunyu/ped/main/files/2063e868-665c-4f30-a013-9b93ba2d3d54.png)

## Potential improvements
Make persons unique based on a combination of name, phone number and email or just phone number and email

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chuajunyu/ped#1

**Comment by joeltio** [comment]
I think this can be a feature suggestion. There is no reason for a system to be designed with so many restrictions to accommodate some edge cases (e.g. changes and reuse of phone numbers, sharing of emails, etc.)

A good testament to this is probably every contacts application. Try adding two contacts with the same numbers. You will realise it accepts it.
